types = {
    1: "Urban",
    2: "Low Sparse Grassland",
    3: "Coniferous Forest",
    4: "Deciduous Conifer Forest",
    5: "Deciduous Broadleaf Forest",
    6: "Evergreen Broadleaf Forests",
    7: "Tall Grasses and Shrubs",
    8: "Bare Desert",
    9: "Upland Tundra",
    10: "Irrigated Grassland",
    11: "Semi Desert",
    12: "Glacier Ice",
    13: "Wooded Wet Swamp",
    14: "Inland Water",
    15: "Sea Water",
    16: "Shrub Evergreen",
    17: "Shrub Deciduous",
    18: "Mixed Forest and Field",
    19: "Evergreen Forest and Fields",
    20: "Cool Rain Forest",
    21: "Conifer Boreal Forest",
    22: "Cool Conifer Forest",
    23: "Cool Mixed Forest",
    24: "Mixed Forest",
    25: "Cool Broadleaf Forest",
    26: "Deciduous Broadleaf Forest",
    27: "Conifer Forest",
    28: "Montane Tropical Forests",
    29: "Seasonal Tropical Forest",
    30: "Cool Crops and Towns",
    31: "Crops and Town",
    32: "Dry Tropical Woods",
    33: "Tropical Rainforest",
    34: "Tropical Degraded Forest",
    35: "Corn and Beans Cropland",
    36: "Rice Paddy and Field",
    37: "Hot Irrigated Cropland",
    38: "Cool Irrigated Cropland",
    39: "Cold Irrigated Cropland",
    40: "Cool Grasses and Shrubs",
    41: "Hot and Mild Grasses and Shrubs",
    42: "Cold Grassland",
    43: "Savanna (Woods)",
    44: "Mire, Bog, Fen",
    45: "Marsh Wetland",
    46: "Mediterranean Scrub",
    47: "Dry Woody Scrub",
    48: "Dry Evergreen Woods",
    49: "Volcanic Rock",
    50: "Sand Desert",
    51: "Semi Desert Shrubs",
    52: "Semi Desert Sage",
    53: "Barren Tundra",
    54: "Cool Southern Hemisphere Mixed Forests",
    55: "Cool Fields and Woods",
    56: "Forest and Field",
    57: "Cool Forest and Field",
    58: "Fields and Woody Savanna",
    59: "Succulent and Thorn Scrub",
    60: "Small Leaf Mixed Woods",
    61: "Deciduous and Mixed Boreal Forest",
    62: "Narrow Conifers",
    63: "Wooded Tundra",
    64: "Heath Scrub",
    65: "Coastal Wetland, NW",
    66: "Coastal Wetland, NE",
    67: "Coastal Wetland, SE",
    68: "Coastal Wetland, SW",
    69: "Polar and Alpine Desert",
    70: "Glacier Rock",
    71: "Salt Playas",
    72: "Mangrove",
    73: "Water and Island Fringe",
    74: "Land, Water, and Shore (see Note 1)",
    75: "Land and Water, Rivers (see Note 1)",
    76: "Crop and Water Mixtures",
    77: "Southern Hemisphere Conifers",
    78: "Southern Hemisphere Mixed Forest",
    79: "Wet Sclerophylic Forest",
    80: "Coastline Fringe",
    81: "Beaches and Dunes",
    82: "Sparse Dunes and Ridges",
    83: "Bare Coastal Dunes",
    84: "Residual Dunes and Beaches",
    85: "Compound Coastlines",
    86: "Rocky Cliffs and Slopes",
    87: "Sandy Grassland and Shrubs",
    88: "Bamboo",
    89: "Moist Eucalyptus",
    90: "Rain Green Tropical Forest",
    91: "Woody Savanna",
    92: "Broadleaf Crops",
    93: "Grass Crops",
    94: "Crops, Grass, Shrubs",
    95: "Evergreen Tree Crop",
    96: "Deciduous Tree Crop",
    99: "Interrupted Areas (Goodes Homolosine Projection)",
    100: "Missing Data",
}
